#!/usr/bin/env zsh


source "$HOME/.config/zsh/zshenv"
source "$HOME/.config/zsh/config"
source "$ZSH/oh-my-zsh.sh"
source "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$HOME/.config/zsh/aliases"
source "$HOME/.config/zsh/gcloud"


# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/michael/.lmstudio/bin"
# End of LM Studio CLI section

