#!/usr/bin/env zsh


source "$HOME/.config/zsh/zshenv"
source "$HOME/.config/zsh/config"
source "$ZSH/oh-my-zsh.sh"
source "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$HOME/.config/zsh/aliases"
source "$HOME/.config/zsh/gcloud"

# Run fastfetch when opening new shell
fastfetch

