#!/usr/bin/env bash

# Init rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
# Init pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Run bash_completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# Git prompt
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
    source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi

# Set locales
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Nicer prompt.
export PS1="\[\e]2;\u@\H:\w\a\]\[$(tput setaf 2)\]\u \[$(tput bold)\] \[$(tput sgr0)\]\[$(tput setaf 2)\]\h\[$(tput setaf 7)\] \w\[$(tput bold)\]\[$(tput setaf 7)\] $ \[$(tput sgr0)\]"
export SUDO_PS1="\[\e]2;\u@\H:\w\a\]\[$(tput setaf 1)\]\u \[$(tput bold)\] \[$(tput sgr0)\]\[$(tput setaf 1)\]\h\[$(tput setaf 7)\] \w\[$(tput bold)\]\[$(tput setaf 7)\] $ \[$(tput sgr0)\]"

# Use colors.
export CLICOLOR=1 # set color to ls
export LSCOLORS=ExFxCxDxBxegedabagacad # set special colors for files / directories in ls

HISTFILE="$XDG_CACHE_HOME/bash/history"

# XDG Base Directory Specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# gnupg
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"

#  less
export LESSHISTFILE="$XDG_CONFIG_HOME/less/history"
export LESSKEY="$XDG_CONFIG_HOME/less/keys"

# Bundler config vars
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundler/cache"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundler/config"
export BUNDLE_USER_PLUGIN='~/.cache/bundler/plugin'

# Set tmuxinator vars
export EDITOR='vim'
