[general]
import = [
    "~/.config/alacritty/themes/tokyo_night_storm.toml"
]
[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
opacity = 1.0
startup_mode = "Windowed"

[keyboard]
bindings = [
    { key = "Return", mods = "Shift", chars = "\n" }
]
