# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 700

[gcloud]
disabled = true

[username]
show_always = true
style_user = "#7aa2f7"
style_root = "#f7768e"
format = " [╭─ $user]($style)"

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold blue)@[$hostname](bold #7dcfff) "

[character]
error_symbol = " [╰─ λ](bold #f7768e)"
success_symbol = " [╰─ λ](bold #7aa2f7)"

[directory]
truncation_symbol = "…/"

